---
repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck (local)
        language: script
        entry: pre_commit_hooks/shellcheck
        types: [shell]
        args: [-e, SC1091]
        additional_dependencies: [shellcheck]

      - id: shellcheck_docker
        name: shellcheck docker (local)
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
